(() => {"use strict";
const rounds=[["すいか","🍉"],["さかな","🐟"],["ひよこ","🐥"],["くじら","🐋"]],extras="あえおきけこたちつぬねのまみむめもらりるれろ";
const sea=document.querySelector("#sea"),prompt=document.querySelector("#prompt"),progress=document.querySelector("#progress"),message=document.querySelector("#message"),finish=document.querySelector("#finish");let n=-1,step=0,current;
function shuffle(a){for(let i=a.length-1;i;i-=1){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function render(){current=rounds[n%rounds.length];step=0;finish.hidden=true;document.querySelector("#picture").textContent=current[1];sea.replaceChildren();progress.replaceChildren();[...current[0]].forEach((c,i)=>{const p=document.createElement("span");p.className=`pip${i===0?" next":""}`;p.textContent=c;progress.append(p);});const chars=shuffle([...current[0],...shuffle([...extras]).slice(0,9)]);chars.forEach((c,i)=>{const b=document.createElement("button");b.type="button";b.className="bubble";b.textContent=c;b.dataset.char=c;b.setAttribute("aria-label",`${c}の あわ`);b.style.left=`${5+(i%6)*15+Math.random()*5}%`;b.style.top=`${8+Math.floor(i/6)*35+Math.random()*8}%`;b.style.animationDelay=`-${Math.random()*2}s`;b.addEventListener("click",()=>choose(b));sea.append(b);});update();}
function update(){prompt.textContent=`「${current[0][step]}」を わろう`;message.textContent=`${step+1}こめの もじだよ`;}
function choose(b){if(b.disabled)return;if(b.dataset.char!==current[0][step]){b.classList.remove("wrong");void b.offsetWidth;b.classList.add("wrong");message.textContent=`つぎは「${current[0][step]}」`;return;}b.disabled=true;b.classList.add("pop");const p=[...progress.children];p[step].className="pip done";step+=1;if(step===current[0].length){document.querySelector("#made").textContent=`${current[1]} ${current[0]}`;setTimeout(()=>finish.hidden=false,350);return;}p[step].classList.add("next");update();}
document.querySelector("#play").addEventListener("click",()=>{document.querySelector("#start").hidden=true;n+=1;render();});document.querySelector("#again").addEventListener("click",()=>{n+=1;render();});document.querySelector("#hint").addEventListener("click",()=>{const b=[...sea.querySelectorAll(".bubble:not(:disabled)")].find(x=>x.dataset.char===current[0][step]);if(b){b.classList.add("hint");setTimeout(()=>b.classList.remove("hint"),1400);}});document.addEventListener("keydown",e=>{const b=[...sea.querySelectorAll(".bubble:not(:disabled)")].find(x=>x.dataset.char===e.key);if(b)b.click();});
})();
