const BASE_URL = new URL("./", window.location.href);
const CATALOG_URL = new URL("../../assets/data/game-stickers.json", BASE_URL);
const FRAME_BASE_URL = new URL("./assets/sticker-carousel-frame-base-v4.png", BASE_URL);
const STATE_KEY = "pono_game_stickers_v1";
const SILHOUETTE_ALPHA_THRESHOLD = 36;
const SILHOUETTE_MASK_MAX_SIZE = 300;

// ===== sticker "real opaque area" sizing (see stickerDisplayMetrics) =====
// window.STICKER_METRICS is provided by sticker-metrics.js (generated by
// scripts/generate_sticker_metrics.py). Missing/absent -> fallback to the
// legacy aspect-ratio-bucket sizing in fitStickerImage().
const STICKER_METRICS = (typeof window !== "undefined" && window.STICKER_METRICS) || {};
const STICKER_SIZE_BASE_PCT = 30; // carousel .sticker-wrap width baseline (%)
const STICKER_SIZE_GAMMA = 0.85; // <1 dampens overcorrection for sparse-fill PNGs
const STICKER_SIZE_CLAMP = [22, 64]; // widthPct clamp (%) for the carousel wrap
const STICKER_SIZE_RARITY_FACTOR = { normal: 1.0, rare: 1.08, super: 1.2 };
const STICKER_DETAIL_BASE_PCT = 38; // detail-view width baseline (%)
const STICKER_DETAIL_CLAMP = [28, 68]; // widthPct clamp (%) for the detail view
// .sticker-stage box within a 4:3 carousel-item (left/right 18%, top 17.5%, bottom 31%)
const STICKER_STAGE_AR = 0.64 / (0.515 * 0.75); // ~1.657
const STICKER_FRAME_GUARD_RATIO = 0.95; // opaque bbox must fit within 95% of the stage box

const ROOMS = [
  { id: "creatures", label: "いきもの" },
  { id: "food", label: "たべもの" },
  { id: "sounds", label: "おと" },
  { id: "tools", label: "どうぐ" },
  { id: "characters", label: "キャラ" },
  { id: "space", label: "うちゅう" },
  { id: "special", label: "とくべつ" },
];

const FLOOR_EXITS = [
  { id: "floor2", label: "うえのかい", status: "じゅんびちゅう" },
];

const RARITY_LABEL = {
  normal: "ふつう",
  rare: "レア",
  super: "スーパーレア",
};

const STICKER_DESC = {
  bonus_quizland_batta_normal: "なぞなぞランドの くさむらで ぴょんと はねてた バッタ。 じつは なぞなぞが だいすき らしい。 むずかしい もんだいほど げんきに ジャンプするよ。",

  // ===== maze (19) =====
  "maze_kani_special_kira_001": "もりの めいろの どこかで きらきらの かいがらを あつめている カニ。 たからさがしが とくいなんだって。",
  "maze_kira_01_odoke_pyon_key_ladder_002": "ぴょんと はねて めいろの みちを あんないしてくれる うさぎ。 くいずの ヒントも こっそり おしえてくれるみたい。",
  "maze_kira_01_odoke_pyon_key_ladder_003": "めいろの おくふかくで みつかった きらめく おうごんの かぎ。 とくべつな とびらを あけられるかもしれないよ。",
  "maze_kira_01_odoke_pyon_key_ladder_004": "つるが からまった きの はしご。 めいろの ふかい あなを おりるときに やくにたつらしい。",
  "maze_kira_02_kujira_glove_acorn_001": "しおを ぷしゅっと ふきあげる にこにこがおの くじら。 めいろの クイズで であえることが あるんだって。",
  "maze_kira_02_kujira_glove_acorn_003": "どんぐりが たっぷり つまった ふくろ。 おじゃまムシに たちむかうときの だいじな どうぐらしい。",
  "maze_normal_lantern_lost_hachi_kabuto_amenbo_chocho_001": "なないろの はねを ひろげて めいろを ひらひら とぶ ちょうちょ。 いろが ぜんぶ そろうと しあわせが くるそうだよ。",
  "maze_normal_lantern_lost_hachi_kabuto_amenbo_chocho_002": "まんまるで ふわふわな ブンブンムシ。 どんぐりボウリングでは ころんと たおれる ピンやくを している。",
  "maze_normal_lantern_lost_hachi_kabuto_amenbo_chocho_003": "よるの めいろを あかりで てらしてくれる、ランタンを もった ポノ。 くらい みちも これで あんしんだね。",
  "maze_normal_lantern_lost_hachi_kabuto_amenbo_chocho_004": "あたまから ちいさな はっぱが のびた もじゃもじゃの みどりの こ。 めいろの しげみに ちょこんと かくれているよ。",
  "maze_normal_lantern_lost_hachi_kabuto_amenbo_chocho_005": "じめんを コツコツ あるく かぶとむしの コツコツムシ。 どんぐりボウリングでは まっすぐ たつ ピンやくだよ。",
  "maze_normal_lantern_lost_hachi_kabuto_amenbo_chocho_006": "みずたまりの うえを すいすい すべる アメンボムシ。 みずの うえを あるく わざが とくいらしい。",
  "maze_ojama_boss_special_kira_001": "めいろの みちに どっしり たっていた おおきな きの みはりばん。 どんぐりが あたると にっこり どいてくれるよ。",
  "maze_power_glove_item": "おもい いわを くだくために てにいれた ちからの てぶくろ。 はめると ぐっと ちからが わいてくるらしい。",
  "bonus_maze_pyon_normal": "しーっと ゆびを たてて リズムを おしえてくれる ぴょんぴょんムシ。 めいろの リズムあそびで であえるよ。",
  "bonus_maze_mayoi_normal": "みちに まよいながらも げんきいっぱいな いもむし、まよいムシ。 どんぐりボウリングの ピンとしても かつやくちゅう。",
  "bonus_maze_odoke_rare": "ひょうきんな しぐさが とくいな くもの おどけムシ。 どんぐりボウリングでは にっこり たつ ピンやくらしい。",
  "bonus_maze_hachi_rare": "はねおとが すこし ちがう、きらきらの ブンブンムシ。 どんぐりボウリングでは とくべつな ピンとして たっているんだって。",
  "bonus_maze_kabuto_super": "つのが ひときわ おおきい、ぴかぴかの コツコツムシ。 どんぐりボウリングを ひかる ピンで もりあげてくれるよ。",

  // ===== quizland (3 / batta は既存) =====
  "quizland_good_stamp_layer_14": "なぞなぞに せいかいすると ぽんと おされる、にっこりがおの はなまるスタンプ。 みるだけで うれしくなっちゃうね。",
  "quizland_note_board_layer_13": "フクロウはかせが こっそり のぞいている メモボード。 なぞなぞの ヒントが かいてあるかもしれないよ。",
  "bonus_quizland_chocho_rare": "なぞなぞランドの はなばたけを ひらひら とぶ きいろい ちょうちょ。 もんだいの まわりを うれしそうに まうんだって。",

  // ===== bento (24) =====
  "bento_best_lunch_special_kira_001": "いろどりべんとうで いちばん ごうかな とくべつランチ。 くまさんごはんに からあげも たまごやきも ぜんぶ そろった ごちそうだよ。",
  "bento_kira_bear_boxes_cat_bear_rice_002": "べんとうばこの なかで くまさんの かたちに かためた ごはん。 まるい みみが じまんの もりつけらしい。",
  "bento_kira_bear_boxes_cat_bear_rice_004": "ねこさんの かおの かたに ぎゅっと つめた ふわふわごはん。 ピンクの はことは なかよしコンビなんだって。",
  "bento_kira_customers_risu_neko_inu_shika_ahiru_araiguma_001": "べんとうやさんに あそびに きた しかさん。 りょうての ひづめを あげて げんきに あいさつするよ。",
  "bento_kira_customers_risu_neko_inu_shika_ahiru_araiguma_002": "みどりの ふきんを だいじに もって べんとうやさんに やってきた アライグマくん。 じゅんびばんたんで まちきれないそうだよ。",
  "bento_kira_customers_risu_neko_inu_shika_ahiru_araiguma_003": "チェックがらの ナフキンを ひろげて まつ わんちゃん。 べんとうが とどくのを たのしみに してるらしい。",
  "bento_kira_customers_risu_neko_inu_shika_ahiru_araiguma_004": "りょうてを たかく あげて よろこぶ りすちゃんが べんとうやさんに とうじょう。 ふさふさの しっぽが じまんなんだって。",
  "bento_kira_customers_risu_neko_inu_shika_ahiru_araiguma_006": "つばさを ぱたぱた ひろげて やってきた あひるさん。 べんとうの においに おおよろこびそうだよ。",
  "bento_kira_items_wiener_pick_ichigo_catboxes_003": "べんとうばこの すみに いつも いる たこさんウインナー。 あしの かずが かぞえきれないほど おおいらしい。",
  "bento_kira_items_wiener_pick_ichigo_catboxes_004": "はんぶんに きると ハートみたいに みえる いちご。 べんとうの さいごに ちょこんと そえられるんだよ。",
  "bento_kira_items_wiener_pick_ichigo_catboxes_005": "おかずに ぷすっと ささる きいろい ほしのピック。 さすだけで べんとうが ぐっと はなやぐんだって。",
  "bento_kira_staff_child_friend_pono_001": "コックぼうしが よく にあう おさげがみの おんなのこスタッフ。 あいさつの えがおが ひょうばんかもしれない。",
  "bento_kira_staff_child_friend_pono_002": "みどりの エプロンで げんきに はたらく スタッフの おとこのこ。 あいさつの こえが いちばん おおきいらしい。",
  "bento_kira_staff_child_friend_pono_003": "きいろい エプロンで べんとうやさんを てつだう ポノ。 おきゃくさんへの あいさつが だいすきだよ。",
  "bento_normal_food_rice_tamago_karaage_broccoli_001": "つやつやで ふっくらした にっこりごはん。 べんとうばこの まんなかに どんと かまえているんだって。",
  "bento_normal_food_rice_tamago_karaage_broccoli_002": "くるくると まかれて できあがった たまごやき。 だんめんの うずもようが みんなに にんきそうだよ。",
  "bento_normal_food_rice_tamago_karaage_broccoli_003": "ころんと まるい すがたが たまらない からあげ。 べんとうばこの なかで いちばんに てが のびるらしい。",
  "bento_normal_food_rice_tamago_karaage_broccoli_004": "もこもこあたまが とくちょうの みどりいろの ブロッコリー。 べんとうの すみっこを ちいさく まもる やくめだよ。",
  "bonus_bento_shika_normal": "はずかしそうに ちょこんと すわる しかさん。 べんとうやさんに はじめて きたばかりなんだって。",
  "bonus_bento_cup_star_normal": "ほしもようが かわいい あおい カップ。 べんとうの おかずを ちいさく わけてくれるんだよ。",
  "bonus_bento_risu_happy_rare": "だいすきな おかずを もらって おおよろこびの りすちゃん。 しっぽまで ぴょんと はねるらしい。",
  "bonus_bento_neko_happy_rare": "りょうてを ぷにっと あげて おおよろこびする ねこさん。 めが きらきら かがやいてるんだよ。",
  "bonus_bento_ahiru_happy_rare": "たべおわって まんぞくそうに つばさを ひろげる あひるさん。 えがおが みどころなんだって。",
  "bonus_bento_pono_present_super": "おきゃくさんに わたす プレゼントばこを かかえる ポノ。 リボンむすびが とくいなのかもしれない。",

  // ===== oto (17) =====
  "oto_kira_highdo_chimes_taiko_animal_kero_001": "おとタッチの ぶたいうらで みつかった きねんボタン。 ケロッチの すがたが ほられてるらしいよ。",
  "oto_kira_highdo_chimes_taiko_animal_kero_002": "おとの せかいの とうだいに つるされてた きんいろの ベル。 なでると りんと すきとおった おとが ひびくらしい。",
  "oto_kira_highdo_chimes_taiko_animal_kero_003": "リズムたいけつの かいじょうで つかわれてた あかい たいこ。 どんと たたくと みんなの こころが はずむそうだよ。",
  "oto_kira_highdo_chimes_taiko_animal_kero_005": "おとタッチの きょくの さいしょに とびだす あかい おんぷ。 げんきいっぱいで ちょっと そそっかしいかもしれない。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_001": "ひだまりの いろを した ファのおんぷ。 のんびりやさんで マイペースに ひびくそうだよ。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_002": "おんかいの いちばん したで どっしり かまえてる ドのおんぷ。 みんなが ここから うたいだすらしいよ。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_003": "ドの となりで ちょこんと まちかまえてる レのおんぷ。 つぎの おとへ つなぐのが とくいなんだって。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_004": "オレンジいろで げんきに はねまわる ソのおんぷ。 たかい おとに ちょうせんするのが すきかもしれない。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_005": "むらさきいろが じまんの ラのおんぷ。 ちょっぴり おしゃれで ゆうがに ひびくらしい。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_007": "みどりいろで きらきらした ミのおんぷ。 あかるい こえで うたうのが だいすきなんだって。",
  "oto_normal_do_re_mi_fa_so_la_si_frog_008": "おんかいの さいごを かざる シのおんぷ。 つぎの ドへ もどりたくて そわそわしてるんだって。",
  "oto_special_kira_robo_gaohn_crown_note_003": "にじいろの わくに つつまれて かがやく おうかんおんぷ。 おとタッチの せかいでも いちばん とくべつな おんぷなんだって。",
  "bonus_oto_robot_laugh_normal": "おとタッチで であう しきしゃロボット ネジマエストロ。 ネジを まくたびに げんきに わらいだすらしい。",
  "bonus_oto_kero_laugh_normal": "ヘッドホンを つけた かえる ケロッチ。 おとタッチの せかいで だれよりも のりのりで おどるんだって。",
  "bonus_oto_lion_roar_rare": "おうかんと マントを まとった ビートキング ガオーン。 とうじょうする たびに おおきな こえで ほえるらしい。",
  "bonus_oto_robot_gears_rare": "ネジを まきなおして めを きらりと ひからせる ネジマエストロ。 ここいちばんの えんそうに むかう しゅんかんなんだって。",
  "bonus_oto_lion_drums_super": "きんいろの わくに かこまれ ドラムを たたきまくる ビートキング ガオーン。 さいきょうの リズムを みせる ひだけ とうじょうするらしい。",

  // ===== quiz-sound (3) =====
  "quiz_sound_bird_frog_bell_ear_badge_002": "えだの うえで きもちよさそうに さえずってた ことり。 おとクイズの もんだいにも こえを かしてくれるらしい。",
  "quiz_sound_bird_frog_bell_ear_badge_003": "はすのはの うえで げんきに うたってた カエル。 みずべの おとを あつめるのが とくいなんだって。",
  "quiz_sound_bird_frog_bell_ear_badge_004": "おとクイズの せかいで いちばん さえてると うわさの おみみ。 どんな ちいさな おとも ききのがさないかもしれない。",

  // ===== sea-album (13) =====
  "sea_album_normal_yadokari_ebi_hitode_isoginchaku_shellkey_sandball_001": "しおだまりを のんびり おさんぽしてた ヤドカリ。 きにいった からを みつけると にっこり わらうらしい。",
  "sea_album_normal_yadokari_ebi_hitode_isoginchaku_shellkey_sandball_002": "しおだまりで ゆらゆら うでを ゆらしていた イソギンチャク。 しおの ながれに あわせて おどりの れんしゅうを しているんだって。",
  "sea_album_normal_yadokari_ebi_hitode_isoginchaku_shellkey_sandball_003": "すなの したから ぴょこんと かおを だした エビ。 ながい ひげで うみの ようすを さぐるのが とくいなんだって。",
  "sea_album_normal_yadokari_ebi_hitode_isoginchaku_shellkey_sandball_004": "しおだまりの すなを まるめて できた すなだま。 なかには ちいさな かいがらが かくれているらしい。",
  "sea_album_normal_yadokari_ebi_hitode_isoginchaku_shellkey_sandball_005": "しおだまりの いわかげで じっと そらを ながめていた ヒトデ。 ほしの かたちを した じまんの からだなんだって。",
  "sea_album_normal_yadokari_ebi_hitode_isoginchaku_shellkey_sandball_006": "うみの おくで きらりと ひかる かいがらの かぎ。 なぞの とびらを あける とくべつな たからものらしい。",
  "sea_album_special_kira_umigame_manta_001": "にじの さす うみを ゆったり およぐ マンタ。 おおきな ひれで にじを はこんでいるという うわさだよ。",
  "sea_album_special_kira_umigame_manta_002": "きらきらの うみを のんびり およぐ ウミガメ。 こうらの なかに うみの ひみつを しまっているのかもしれない。",
  "bonus_sea_album_hermit_crab_normal": "おひさまの したで うとうと おひるねしていた ヤドカリ。 からの なかは あったかくて きもちいいんだって。",
  "bonus_sea_album_sea_star_normal": "しおだまりで げんきよく くるんと まわってみせた ヒトデ。 わらうと ほしが ひとつ ふえたみたいに かがやくよ。",
  "bonus_sea_album_horseshoe_crab_rare": "しおだまりの おくに ひそむ こがねいろの カブトガニ。 ながい しっぽは まほうの つえなんだって。",
  "bonus_sea_album_sea_anemone_rare": "きらきらの ひかりに つつまれた めずらしい イソギンチャク。 うでを ぐるりと ひろげて ひかりを あつめているらしい。",
  "bonus_sea_album_clownfish_super": "しおだまりの ひかりの なかを すいすい およぐ カクレクマノミ。 しましまもようが じまんの おしゃれなんだって。",

  // ===== undersea-cave (8) =====
  "undersea_cave_whale_lightfood_bubble_blueshell_001": "かいていどうくつの おくで ひかりを あつめる ひかるしんじゅ。 よるの あいだに もっと きらきらするらしい。",
  "undersea_cave_whale_lightfood_bubble_blueshell_004": "どうくつの かべに かざられていた つきのたて。 まんまるの つきの よるだけ ほのかに ひかるんだって。",
  "undersea_special_squid_layer_15": "かいていどうくつの ひかりの なかを ふわふわ ただよう ひかるイカ。 からだが にじいろに そまることが あるらしい。",
  "undersea_special_whale_layer_01": "どうくつの おくの ひろい うみを ゆうゆうと およぐ ジンベエザメ。 せなかの もようは ほしの ちずなんだって。",
  "bonus_undersea_cave_octopus_normal": "かいていどうくつで にこにこ わらっていた タコ。 うれしいことが あると ハートの あわを だすんだって。",
  "bonus_undersea_cave_pearl_shell_normal": "どうくつの ふかい ところで みつかった しんじゅのかい。 なかの しんじゅは よるの いろを うつすらしい。",
  "bonus_undersea_cave_whale_rare": "どうくつの いりぐちで ぱくっと くちを あけて わらう ちびジンベエ。 まだ こどもだけど およぐのが だいすきらしい。",
  "bonus_undersea_cave_bell_bubble_rare": "あわの なかに ういていた きんいろの あわベル。 ゆれるたびに やさしい おとが なるんだって。",

  // ===== puzzle (7) =====
  "puzzle_kira_fox_crow_hedgehog_owl_raccoon_redpiece_001": "もりの こみちで ひろった ピースを だいじに かかえてた アライグマ。 しましまの しっぽを ゆらゆら ゆらすのが くせなんだって。",
  "puzzle_kira_fox_crow_hedgehog_owl_raccoon_redpiece_002": "もりの おくで であった キツネ。 てを あげて あいさつするのが とくいらしい。",
  "puzzle_kira_fox_crow_hedgehog_owl_raccoon_redpiece_003": "きのうえから みんなを みまもってた、 おしゃべりずきな カラス。 もりじゅうに いつも なにか つぶやいてるよ。",
  "puzzle_kira_fox_crow_hedgehog_owl_raccoon_redpiece_004": "もりの としょかんに くらす ものしりな フクロウの はかせ。 むずかしい ほんも スラスラ よみとけるらしい。",
  "puzzle_kira_fox_crow_hedgehog_owl_raccoon_redpiece_005": "おちばの したから ひょっこり あらわれた、 もりの ハリネズミ。 とげとげの せなかは さわると やわらかいかもしれない。",
  "puzzle_normal_usagi_risu_kojika_001": "もりの はずれで うまれたての ピースを みつけた こじか。 せなかの もようは ほしぞらに にてるそうだよ。",
  "puzzle_normal_usagi_risu_kojika_002": "もりの くさはらで ぴんくの ピースを みつけた うさぎ。 ながい みみで とおくの おとまで きこえちゃうんだって。",

  // ===== starparodier (7) =====
  "starparodier_starboat_beam_mecha_planet_001": "うちゅうの かなたを ただよってた まんまるの メカ。 アンテナで とおい ほしの おとを ひろってるらしい。",
  "starparodier_starboat_beam_mecha_planet_002": "きらきらの ほしの わっかを まとった わくせい。 よるに なると リングが もっと つよく ひかるんだって。",
  "starparodier_starboat_beam_mecha_planet_004": "うちゅうを たのしそうに とびまわる ポノの だいすきな ロケット。 まどから のぞく にこにこがおが めじるしだよ。",
  "bonus_starparodier_ship_pono_normal": "ポノロケットを ぎゅっと ちいさくした ミニチュアばん。 すいすい そらを とぶ すがたが かわいいらしい。",
  "bonus_starparodier_zako_enemy_rare": "うちゅうの みちを まいにち みまわってた まんまるの ドローン。 みどりの めを ぴかぴか させて なかよく あいさつしてくれるそうだよ。",
  "bonus_starparodier_power_star_rare": "うちゅうに ぽっかり うかんでた にこにこの ほし。 ちからを わけてくれる げんきの もとなんだって。",
  "bonus_starparodier_starbrain_super": "うちゅうの おくふかくに ねむっていた ふしぎな コア。 ほしぼしの ちからを あつめて きらきら ひかってるかもしれない。",

  // ===== wordmatch (6) =====
  "wordmatch_name_voice_shape_stamp_002": "ことばの くにで みつけた どんぐりの メモようし。 すきな ことばを かきとめておくのに ぴったりらしい。",
  "wordmatch_name_voice_shape_stamp_003": "げんきな メガホンが、 ことばの くにに ひびいていたよ。 すてきな ことばを とおくまで とどけてくれるんだって。",
  "wordmatch_name_voice_shape_stamp_004": "ことばの くにで つかわれてた きのぬくもりの スタンプ。 ぴったりの こたえに ぽんと おされるそうだよ。",
  "bonus_wordmatch_ichigo_normal": "あかく みのった いちごを、 ことばの くにの はたけで みつけたよ。 あまい かおりに ことばも はずむかもしれない。",
  "bonus_wordmatch_hana_rare": "ことばの くにに さいていた にこにこの おはな。 かぜが ふくたびに たのしい ことばを つぶやくらしい。",
  "bonus_wordmatch_rocket_rare": "いきおいよく とびたった ロケットは、 ことばの くにから やってきたんだって。 あたらしい ことばを さがしに でかけたよ。",

  // ===== zukan (14) =====
  "zukan_bear_layer_05": "もりの おくを たんけんしていた くまの ポノ。 にっこり わらうと、 まわりまで あたたかく なる きが するよ。",
  "zukan_dog_layer_12": "しっぽを ふりふり、 もりの いりぐちで まっていた こいぬ。 あかい くびわが じまんの ポイントなんだって。",
  "zukan_giraffe_layer_08": "もりの はずれで たかい きの はっぱを みつけて にっこりした キリン。 ながい くびが じまんで、 いつも しゃきっと のばしているんだって。",
  "zukan_lion_layer_03": "もりの ひだまりで きもちよさそうに たっていた ちいさな ライオン。 ふわふわの たてがみが じまんそうだよ。",
  "zukan_penguin_layer_04": "もりの さきに ある こおりの くにから あそびに きた ペンギン。 ふりむいた よこがおが とくに にんきかもしれない。",
  "zukan_special_kabuto_layer_02": "おおきな きの みきの うえで であった、 とくべつな カブトムシ。 つのを たかく あげて みつの あじみに むちゅうらしい。",
  "zukan_squirrel_fox_mushroom_leaf_badge_001": "もりの おくで みつかった はっぱの かたちの バッジ。 リスや キノコの えが きらきら うかんで みえるんだって。",
  "zukan_squirrel_fox_mushroom_leaf_badge_002": "しげみから そっと かおを だした、 もりの こぎつね。 しずかに すわって みんなを みまもるのが すきらしい。",
  "zukan_squirrel_fox_mushroom_leaf_badge_003": "じめんから ひょっこり かおを だした キノコ。 もりに あめが ふった つぎの あさに、 いちばん げんきに なるそうだよ。",
  "zukan_squirrel_fox_mushroom_leaf_badge_004": "もりの くさむらで どんぐりを だいじそうに かかえていた リス。 ひとつ みつけると もう ひとつ さがしたく なるらしい。",
  "zukan_squirrel_layer_11": "もりの きの えだで くびを かしげていた リス。 なにか かんがえごとを している ときの くせなんだって。",
  "bonus_zukan_penguin_normal": "もりの ゆきだまりに ちょこんと たっていた ペンギン。 まっすぐ たって ごあいさつするのが とくいだよ。",
  "bonus_zukan_kabutomushi_rare": "もりの きかげで うでを くんで どやがおしていた カブトムシ。 じつは てれやさんかもしれない。",
  "bonus_zukan_shika_super": "もりの こみちで であった ちいさな こじか。 りっぱに のびてきた つのが じまんなんだって。",

  // ===== writing-mori (7) =====
  "writing_mori_a_mirumaru_seed_flower_001": "もじの もりに さいた はなの メダル。「あ」の もじが したの ほうに そっと うかんで いるんだって。",
  "writing_mori_a_mirumaru_seed_flower_002": "もじの もりに すむ ミルマル。 まいにち たのしそうに もじの れんしゅうを しているらしい。",
  "writing_mori_a_mirumaru_seed_flower_003": "もじの もりの すみっこで めを だした ふたば。 ミルマルが まいにち みずを あげて そだてているそうだよ。",
  "writing_mori_a_mirumaru_seed_flower_004": "きの もじ「あ」が、 もじの もりに どっしり たっているよ。 てっぺんから ちいさな めが ひょっこり でて いるよ。",
  "bonus_writing_mori_milmaru_wave_normal": "あさの もじの もりで おおきく てを ふる ミルマル。 げんきな あいさつは もりじゅうに ひびくんだって。",
  "bonus_writing_mori_milmaru_relaxed_rare": "よるの もじの もりで うとうと している おやすみミルマル。 ねむる まえに ほしを かぞえる くせが あるらしい。",
  "bonus_writing_mori_milmaru_cookie_super": "もじの もりの おいわいの ひに あらわれる おかしミルマル。 ほしの クッキーを たからものみたいに かかえているよ。",

  // ===== book-bonus (5 / 特典系: 絵本特典ニュアンスを維持) =====
  // 2026-07-06: book_bonus_duck_rare (アヒル) は 9→8 枚化で catalog から削除済み。この desc も削除。
  "book_bonus_pono_book_rare": "えほんの なかで きいろい エプロンの ポノが ページを めくって まっているよ。 えほんと いっしょに やってきた とくべつな シール。",
  "book_bonus_mama_pono_super": "えほんの ひとこまで ほおを よせあう ママと ポノ。 えほんを ひらくと であえる、 あたたかい おもいでの シール。",
  "book_bonus_hedgehog_rare": "えほんの もりみちを とことこ あるいていた ハリネズミ。 えほんに そっと そえられた、 ちいさな シール。",
  "book_bonus_friends_super": "えほんの なかまたちが みんなで あつまった、 にぎやかな ひとこま。 えほんを ひらくたびに あえる、 なかよしの シール。",
  "book_bonus_ehon_medal_super": "えほんの ひょうしを あけると あらわれる、 どんぐりの メダル。 えほんと いっしょに とどく、 きねんの シール。",

  // ===== monster_math (4) =====
  "mm_tenmegane": "めがねの まん丸モンスター。 ぴったりの かずを たべるのが だいすき。",
  "mm_kakuren": "かくれんぼの めいじん。 ぼうしで こそっと かくして あそぶ。",
  "mm_both_modes": "テンメガネと カクレン、なかよし ツーショット。 ふたりで ぱちり。",
  "mm_perfect": "きらきらの ほしぼうしと まん丸メガネ。 ぜんぶ せいかいの あかし。",
};

const els = {
  loading: document.getElementById("loading"),
  app: document.getElementById("app"),
  backToMap: document.getElementById("backToMap"),
  homeButton: document.getElementById("homeButton"),
  mapScreen: document.getElementById("mapScreen"),
  mapNotice: document.getElementById("mapNotice"),
  screenKicker: document.getElementById("screenKicker"),
  roomTitle: document.getElementById("roomTitle"),
  roomTabs: document.getElementById("roomTabs"),
  countChip: document.getElementById("countChip"),
  carouselShell: document.getElementById("carouselShell"),
  carouselViewport: document.getElementById("carouselViewport"),
  carouselLayer: document.getElementById("carouselLayer"),
  prevButton: document.getElementById("prevButton"),
  nextButton: document.getElementById("nextButton"),
  randomButton: document.getElementById("randomButton"),
  bottomBar: document.getElementById("bottomBar"),
  positionChip: document.getElementById("positionChip"),
  progressFill: document.getElementById("progressFill"),
  detailOverlay: document.getElementById("detailOverlay"),
  detailPanel: document.querySelector(".detail-panel"),
  closeDetail: document.getElementById("closeDetail"),
  detailFrame: document.getElementById("detailFrame"),
  detailImage: document.getElementById("detailImage"),
  detailSerial: document.getElementById("detailSerial"),
  detailName: document.getElementById("detailName"),
  detailDesc: document.getElementById("detailDesc"),
  detailTags: document.getElementById("detailTags"),
};

const state = {
  stickers: [],
  filtered: [],
  roomId: "",
  index: 0,
  touchStartX: 0,
  touchStartY: 0,
  touchStartTime: 0,
  touchActive: false,
  touchPointerId: 0,
  suppressClickUntil: 0,
  glideTimer: 0,
  isGliding: false,
  lastFocus: null,
  mapNoticeTimer: 0,
};

const silhouetteMaskCache = new Map();

init();

async function init() {
  try {
    const catalog = await loadCatalog();
    state.stickers = flattenCatalog(catalog);
    applyOwnership(state.stickers);
    renderMapRooms();
    wireEvents();
    const initialRoomId = readInitialRoomId();
    if (initialRoomId) showRoom(initialRoomId, { updateUrl: false });
    else showMap({ updateUrl: false });
    els.loading.hidden = true;
  } catch (error) {
    console.error(error);
    els.loading.classList.add("is-error");
    els.loading.textContent = "よみこめなかったよ";
  }
}

async function loadCatalog() {
  const response = await fetch(`${CATALOG_URL.href}?_=${Date.now()}`, { cache: "no-store" });
  if (!response.ok) throw new Error(`catalog fetch failed: ${response.status}`);
  return response.json();
}

function flattenCatalog(catalog) {
  const pages = catalog && catalog.pages ? catalog.pages : {};
  const stickers = [];

  Object.entries(pages).forEach(([pageId, page]) => {
    const pageStickers = Array.isArray(page.stickers) ? page.stickers : [];
    pageStickers.forEach((sticker) => {
      if (!sticker || !sticker.id) return;
      const serial = Number.parseInt(sticker.serial || "0", 10) || 0;
      const item = {
        ...sticker,
        serial,
        pageId,
        pageTitle: page.title || "シール",
        imageUrl: resolveAsset(sticker.img),
        desc: STICKER_DESC[sticker.id] || "",
      };
      item.roomId = assignRoom(item);
      stickers.push(item);
    });
  });

  return stickers.sort((a, b) => a.serial - b.serial);
}

function resolveAsset(path) {
  if (!path) return "";
  if (/^(https?:|data:|\/|\.\.?\/)/.test(path)) return path;
  return new URL(`../../${path}`, BASE_URL).href;
}

function applyOwnership(stickers) {
  const owned = readOwnedIds();
  const useDemo = owned.size === 0;
  stickers.forEach((sticker) => {
    sticker.owned = useDemo ? demoOwned(sticker) : owned.has(sticker.id);
  });
}

function readOwnedIds() {
  const ids = new Set();
  try {
    const raw = localStorage.getItem(STATE_KEY);
    const parsed = raw ? JSON.parse(raw) : null;
    const pages = parsed && parsed.pages && typeof parsed.pages === "object" ? parsed.pages : {};
    Object.values(pages).forEach((page) => {
      const owned = page && page.owned && typeof page.owned === "object" ? page.owned : {};
      Object.entries(owned).forEach(([id, record]) => {
        const count = record && typeof record === "object" ? Number(record.count || 0) : Number(record || 0);
        if (count > 0) ids.add(id);
      });
    });
  } catch (_) {
    return ids;
  }
  return ids;
}

function demoOwned(sticker) {
  if (sticker.pageId === "book-bonus") return sticker.serial % 2 === 0;
  if (sticker.rarity === "super") return sticker.serial % 3 === 0;
  return sticker.serial % 4 !== 0;
}

function renderMapRooms() {
  if (!els.mapScreen) return;
  els.mapScreen.querySelectorAll("[data-room-id]").forEach((button) => {
    const room = ROOMS.find((item) => item.id === button.dataset.roomId);
    if (!room) return;
    const list = state.stickers.filter((sticker) => sticker.roomId === room.id);
    const owned = list.filter((sticker) => sticker.owned).length;
    button.setAttribute("aria-label", `${room.label}のへや`);
    button.replaceChildren(createMapLabel(room.label, `${owned} / ${list.length}`));
  });
  renderMapExits();
}

function renderMapExits() {
  els.mapScreen.querySelectorAll("[data-floor-id]").forEach((button) => {
    const exit = FLOOR_EXITS.find((item) => item.id === button.dataset.floorId);
    if (!exit) return;
    button.setAttribute("aria-label", `${exit.label} ${exit.status}`);
    button.replaceChildren(createMapLabel(exit.label, exit.status));
  });
}

function createSpan(className, text) {
  const span = document.createElement("span");
  span.className = className;
  span.textContent = text;
  return span;
}

function createMapLabel(name, count) {
  const label = document.createElement("span");
  label.className = "map-room__label";
  label.append(
    createSpan("map-room__name", name),
    createSpan("map-room__count", count)
  );
  return label;
}

function renderRoomTabs() {
  if (!els.roomTabs) return;
  els.roomTabs.replaceChildren();
  ROOMS.forEach((room) => {
    const button = document.createElement("button");
    button.type = "button";
    button.className = "room-tab";
    button.dataset.roomId = room.id;
    button.textContent = room.label;
    button.setAttribute("aria-label", `${room.label}のへや`);
    els.roomTabs.appendChild(button);
  });
}

function selectRoom(roomId) {
  const room = ROOMS.find((item) => item.id === roomId) || ROOMS[0];
  state.roomId = room.id;
  state.filtered = state.stickers.filter((sticker) => sticker.roomId === room.id);
  state.index = firstOwnedIndex(state.filtered);

  els.roomTitle.textContent = room.label;
  document.querySelectorAll(".room-tab").forEach((tab) => {
    tab.classList.toggle("is-active", tab.dataset.roomId === room.id);
    tab.setAttribute("aria-selected", tab.dataset.roomId === room.id ? "true" : "false");
  });

  renderCarousel();
  updateStatus();
}

function showMap({ updateUrl = true } = {}) {
  state.roomId = "";
  state.filtered = [];
  els.app.classList.add("is-map");
  els.app.classList.remove("is-room");
  els.mapScreen.hidden = false;
  els.carouselShell.hidden = true;
  els.bottomBar.hidden = true;
  els.backToMap.hidden = true;
  els.countChip.hidden = true;
  els.screenKicker.textContent = "マップ";
  els.roomTitle.textContent = "シールミュージアム";
  closeDetail();
  hideMapNotice();
  renderMapRooms();
  if (updateUrl) setRoomUrl("");
}

function showRoom(roomId, { updateUrl = true } = {}) {
  const room = ROOMS.find((item) => item.id === roomId) || ROOMS[0];
  selectRoom(room.id);
  els.app.classList.remove("is-map");
  els.app.classList.add("is-room");
  els.mapScreen.hidden = true;
  els.carouselShell.hidden = false;
  els.bottomBar.hidden = false;
  els.backToMap.hidden = false;
  els.countChip.hidden = false;
  els.screenKicker.textContent = "シールミュージアム";
  if (updateUrl) setRoomUrl(room.id);
  requestAnimationFrame(updateCarouselLayout);
}

function setRoomUrl(roomId) {
  const url = new URL(window.location.href);
  if (roomId) url.searchParams.set("room", roomId);
  else url.searchParams.delete("room");
  window.history.pushState({ roomId }, "", url);
}

function firstOwnedIndex(list) {
  const found = list.findIndex((sticker) => sticker.owned);
  return found >= 0 ? found : 0;
}

function renderCarousel() {
  els.carouselLayer.replaceChildren();
  const list = state.filtered;
  list.forEach((sticker, index) => {
    const item = createCarouselItem(sticker, index);
    els.carouselLayer.appendChild(item);
  });
  updateCarouselLayout();
}

function createCarouselItem(sticker, index) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "carousel-item";
  button.dataset.index = String(index);
  button.dataset.stickerId = sticker.id;
  const rarity = sticker.rarity || "normal";
  button.dataset.rarity = rarity;
  if (rarity === "rare" || rarity === "super") {
    button.classList.add("is-rarity-special", `is-rarity-${rarity}`);
  }
  if (!sticker.owned) button.classList.add("is-locked");
  button.setAttribute("aria-label", sticker.owned ? sticker.name : "まだ");

  const frame = document.createElement("span");
  frame.className = "display-frame";

  const frameImage = document.createElement("img");
  frameImage.className = "frame-base-image";
  frameImage.src = FRAME_BASE_URL.href;
  frameImage.alt = "";
  frameImage.draggable = false;
  frameImage.loading = "eager";

  const stickerStage = document.createElement("span");
  stickerStage.className = "sticker-stage";

  if (rarity === "rare" || rarity === "super") {
    const sparkles = document.createElement("span");
    sparkles.className = "rarity-sparkles";
    sparkles.setAttribute("aria-hidden", "true");
    for (let i = 0; i < (rarity === "super" ? 8 : 5); i += 1) {
      const star = document.createElement("span");
      star.className = "rarity-sparkle";
      star.textContent = "✦";
      sparkles.appendChild(star);
    }
    frame.appendChild(sparkles);
  }

  const stickerWrap = document.createElement("span");
  stickerWrap.className = "sticker-wrap";

  const img = document.createElement("img");
  img.src = sticker.imageUrl;
  img.alt = sticker.owned ? sticker.name : "";
  img.draggable = false;
  img.loading = "lazy";
  const applyImageFit = () => {
    fitStickerImage(stickerWrap, img, sticker);
    const silhouette = stickerWrap.querySelector(".locked-silhouette");
    if (!sticker.owned && silhouette) applySolidSilhouetteMask(silhouette, img, "--silhouette-image");
  };
  img.addEventListener("load", applyImageFit, { once: true });
  stickerWrap.appendChild(img);
  if (!sticker.owned) {
    const silhouette = document.createElement("span");
    silhouette.className = "locked-silhouette";
    silhouette.setAttribute("aria-hidden", "true");
    silhouette.style.setProperty("--silhouette-image", cssImageUrl(sticker.imageUrl));
    stickerWrap.appendChild(silhouette);
  }
  if (img.complete) applyImageFit();
  stickerStage.appendChild(stickerWrap);

  if (!sticker.owned) {
    const lock = document.createElement("span");
    lock.className = "lock-dot";
    lock.textContent = "?";
    stickerStage.appendChild(lock);
  }

  frame.append(frameImage, stickerStage);

  const label = document.createElement("span");
  label.className = "frame-label";
  label.textContent = sticker.owned ? sticker.name : "まだ";

  button.append(frame, label);
  return button;
}

function fitStickerImage(wrap, img, sticker) {
  const ratio = img.naturalWidth && img.naturalHeight ? img.naturalWidth / img.naturalHeight : 1;
  wrap.style.setProperty("--sticker-aspect", String(clamp(ratio, 0.36, 2.1)));

  const metrics = sticker ? stickerDisplayMetrics(sticker) : null;
  if (metrics) {
    wrap.classList.remove("is-tall", "is-wide");
    wrap.style.setProperty("--sticker-width-pct", `${metrics.widthPct.toFixed(2)}%`);
    wrap.style.setProperty("--sticker-offset-x", `${metrics.offsetXPct.toFixed(2)}%`);
    wrap.style.setProperty("--sticker-offset-y", `${metrics.offsetYPct.toFixed(2)}%`);
  } else {
    wrap.style.removeProperty("--sticker-width-pct");
    wrap.style.removeProperty("--sticker-offset-x");
    wrap.style.removeProperty("--sticker-offset-y");
    wrap.classList.toggle("is-tall", ratio < 0.78);
    wrap.classList.toggle("is-wide", ratio > 1.28);
  }
}

// Computes a "real opaque pixel area" based display size for a sticker, so
// that PNGs with lots of transparent padding (low fill ratio) don't render
// smaller than tightly-cropped PNGs of the same rarity, and vice versa.
// Returns null when STICKER_METRICS has no entry for this sticker (caller
// falls back to the legacy aspect-ratio-bucket sizing).
// 前提: このガード/オフセット計算は、キャンバス比率が --sticker-aspect の clamp 範囲
// [0.36, 2.1] 内にあり、img が wrap を dominant 軸で 100% 充填する前提。現行135枚は
// 全て範囲内 (0.559〜1.213)。範囲外の極端な縦横比のシールを将来追加する場合は
// letterbox 分の補正が必要。
function stickerDisplayMetrics(sticker) {
  const m = sticker && STICKER_METRICS[sticker.id];
  if (!m) return null;
  const [width, height, bboxX, bboxY, bboxW, bboxH, area] = m;
  if (!width || !height || !bboxW || !bboxH || !area) return null;

  const sqrtArea = Math.sqrt(area);
  if (!sqrtArea) return null;

  const rarityFactor = STICKER_SIZE_RARITY_FACTOR[sticker.rarity] ?? 1.0;
  const raw = width / sqrtArea; // canvas-padding correction term

  let widthPct = STICKER_SIZE_BASE_PCT * rarityFactor * Math.pow(raw, STICKER_SIZE_GAMMA);
  widthPct = clamp(widthPct, STICKER_SIZE_CLAMP[0], STICKER_SIZE_CLAMP[1]);

  // Frame guard: keep the opaque bbox within STICKER_FRAME_GUARD_RATIO of the
  // .sticker-stage box in both dimensions (protects tall/wide outliers).
  const wfMaxW = (STICKER_FRAME_GUARD_RATIO * width) / bboxW;
  const wfMaxH = (STICKER_FRAME_GUARD_RATIO * width) / (STICKER_STAGE_AR * bboxH);
  const wfMaxPct = 100 * Math.min(wfMaxW, wfMaxH);
  widthPct = Math.min(widthPct, wfMaxPct);

  let detailWidthPct = STICKER_DETAIL_BASE_PCT * rarityFactor * Math.pow(raw, STICKER_SIZE_GAMMA);
  detailWidthPct = clamp(detailWidthPct, STICKER_DETAIL_CLAMP[0], STICKER_DETAIL_CLAMP[1]);

  // bbox-center -> canvas-center offset, expressed as a % of the canvas (==
  // % of the wrap/img own box, since wrap AR matches canvas AR exactly so
  // object-fit:contain applies zero letterboxing).
  const offsetXPct = ((width / 2 - (bboxX + bboxW / 2)) / width) * 100;
  const offsetYPct = ((height / 2 - (bboxY + bboxH / 2)) / height) * 100;

  return { widthPct, detailWidthPct, offsetXPct, offsetYPct };
}

function cssImageUrl(url) {
  const safeUrl = String(url || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `url("${safeUrl}")`;
}

async function applySolidSilhouetteMask(target, img, propertyName) {
  if (!target || !img || !img.naturalWidth || !img.naturalHeight) return;
  const sourceUrl = img.currentSrc || img.src;
  const maskUrl = await createSolidSilhouetteMask(sourceUrl, img);
  if (!maskUrl || !target.isConnected || (img.currentSrc || img.src) !== sourceUrl) return;
  target.style.setProperty(propertyName, cssImageUrl(maskUrl));
}

async function createSolidSilhouetteMask(sourceUrl, img) {
  if (silhouetteMaskCache.has(sourceUrl)) return silhouetteMaskCache.get(sourceUrl);
  try {
    const scale = Math.min(1, SILHOUETTE_MASK_MAX_SIZE / Math.max(img.naturalWidth, img.naturalHeight));
    const width = Math.max(1, Math.round(img.naturalWidth * scale));
    const height = Math.max(1, Math.round(img.naturalHeight * scale));
    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    const context = canvas.getContext("2d", { willReadFrequently: true });
    if (!context) return "";
    context.clearRect(0, 0, width, height);
    context.drawImage(img, 0, 0, width, height);
    const imageData = context.getImageData(0, 0, width, height);
    const data = imageData.data;
    for (let i = 0; i < data.length; i += 4) {
      const filled = data[i + 3] > SILHOUETTE_ALPHA_THRESHOLD ? 255 : 0;
      data[i] = 0;
      data[i + 1] = 0;
      data[i + 2] = 0;
      data[i + 3] = filled;
    }
    context.putImageData(imageData, 0, 0);
    const maskUrl = canvas.toDataURL("image/png");
    silhouetteMaskCache.set(sourceUrl, maskUrl);
    return maskUrl;
  } catch (_) {
    silhouetteMaskCache.set(sourceUrl, "");
    return "";
  }
}

function carouselStep() {
  const viewportWidth = els.carouselViewport.clientWidth || window.innerWidth;
  return clamp(viewportWidth * 0.36, 220, 420);
}

function updateCarouselLayout() {
  const list = state.filtered;
  const total = list.length;
  const step = carouselStep();

  Array.from(els.carouselLayer.children).forEach((item) => {
    const index = Number(item.dataset.index || 0);
    const offset = wrappedOffset(index, state.index, total);
    const distance = Math.abs(offset);
    const active = offset === 0;
    const visible = distance <= 3;
    const scale = active ? 1 : distance === 1 ? 0.76 : distance === 2 ? 0.58 : 0.42;
    const opacity = visible ? (active ? 1 : distance === 1 ? 0.82 : distance === 2 ? 0.46 : 0.12) : 0;
    const blur = visible ? (distance >= 3 ? 1.8 : 0) : 3;

    item.classList.toggle("is-active", active);
    item.classList.toggle("is-far", !visible);
    item.style.setProperty("--item-x", `${offset * step}px`);
    item.style.setProperty("--item-scale", String(scale));
    item.style.setProperty("--item-opacity", String(opacity));
    item.style.setProperty("--item-blur", `${blur}px`);
    item.style.setProperty("--item-events", visible ? "auto" : "none");
    item.style.zIndex = String(50 - distance);
    item.tabIndex = active ? 0 : -1;
    item.setAttribute("aria-hidden", visible ? "false" : "true");
  });
}

function wrappedOffset(index, activeIndex, total) {
  if (total <= 0) return 0;
  let offset = index - activeIndex;
  if (offset > total / 2) offset -= total;
  if (offset < -total / 2) offset += total;
  return offset;
}

function updateStatus() {
  const list = state.filtered;
  const total = list.length;
  const owned = list.filter((sticker) => sticker.owned).length;
  els.countChip.textContent = `${owned} / ${total}`;
  els.positionChip.textContent = total ? `${state.index + 1} / ${total}` : "0 / 0";
  els.progressFill.style.width = total ? `${((state.index + 1) / total) * 100}%` : "0%";
}

function goTo(index, { cancelMotion = true } = {}) {
  const total = state.filtered.length;
  if (!total) return;
  if (cancelMotion) cancelGlide();
  state.index = (index + total) % total;
  updateCarouselLayout();
  updateStatus();
}

function next() {
  goTo(state.index + 1);
}

function prev() {
  goTo(state.index - 1);
}

function glideBy(delta) {
  const total = state.filtered.length;
  if (!total) return;
  const direction = delta > 0 ? 1 : -1;
  let remaining = Math.min(Math.abs(delta), Math.max(1, total - 1));
  if (!remaining) return;

  cancelGlide();
  state.isGliding = true;
  els.app.classList.add("is-gliding");
  const stepMs = remaining >= 5 ? 104 : remaining >= 3 ? 118 : 136;
  state.suppressClickUntil = performance.now() + remaining * stepMs + 420;

  const step = () => {
    goTo(state.index + direction, { cancelMotion: false });
    remaining -= 1;
    if (remaining <= 0) {
      state.glideTimer = window.setTimeout(() => {
        state.glideTimer = 0;
        state.isGliding = false;
        els.app.classList.remove("is-gliding");
      }, 170);
      return;
    }
    state.glideTimer = window.setTimeout(step, stepMs);
  };

  step();
}

function cancelGlide() {
  if (state.glideTimer) {
    window.clearTimeout(state.glideTimer);
    state.glideTimer = 0;
  }
  state.isGliding = false;
  els.app.classList.remove("is-gliding");
}

function setDragOffset(value) {
  els.carouselLayer.style.setProperty("--drag-x", `${value}px`);
}

function resetDragOffset() {
  els.carouselLayer.style.removeProperty("--drag-x");
  els.app.classList.remove("is-dragging");
}

function openDetail(sticker) {
  state.lastFocus = document.activeElement;
  els.detailOverlay.hidden = false;
  els.detailPanel.classList.toggle("is-locked", !sticker.owned);
  els.detailImage.src = sticker.imageUrl;
  els.detailImage.alt = sticker.owned ? sticker.name : "";
  const detailMetrics = stickerDisplayMetrics(sticker);
  if (detailMetrics) {
    els.detailFrame.style.setProperty("--detail-width-pct", `${detailMetrics.detailWidthPct.toFixed(2)}%`);
    els.detailFrame.style.setProperty("--detail-offset-x", `${detailMetrics.offsetXPct.toFixed(2)}%`);
    els.detailFrame.style.setProperty("--detail-offset-y", `${detailMetrics.offsetYPct.toFixed(2)}%`);
  } else {
    els.detailFrame.style.removeProperty("--detail-width-pct");
    els.detailFrame.style.removeProperty("--detail-offset-x");
    els.detailFrame.style.removeProperty("--detail-offset-y");
  }
  if (sticker.owned) {
    els.detailFrame.style.removeProperty("--detail-silhouette-image");
  } else {
    els.detailFrame.style.setProperty("--detail-silhouette-image", cssImageUrl(sticker.imageUrl));
    const applyDetailMask = () => applySolidSilhouetteMask(els.detailFrame, els.detailImage, "--detail-silhouette-image");
    els.detailImage.addEventListener("load", applyDetailMask, { once: true });
    if (els.detailImage.complete) applyDetailMask();
  }
  els.detailSerial.textContent = String(sticker.serial || 0).padStart(3, "0");
  els.detailName.textContent = sticker.owned ? sticker.name : "まだ";
  const desc = sticker.owned ? sticker.desc || "" : "";
  if (els.detailDesc) {
    els.detailDesc.textContent = desc;
    els.detailDesc.hidden = !desc;
  }
  els.detailTags.replaceChildren(
    createTag(sticker.owned ? "あつめた" : "まだ", true),
    createTag(RARITY_LABEL[sticker.rarity] || "ふつう"),
    createTag(roomLabel(sticker.roomId)),
    createTag(sticker.pageTitle || "シール")
  );
  els.closeDetail.focus();
}

function closeDetail() {
  const wasHidden = els.detailOverlay.hidden;
  els.detailOverlay.hidden = true;
  if (!wasHidden && state.lastFocus && typeof state.lastFocus.focus === "function") {
    state.lastFocus.focus();
  }
}

function createTag(text, hot = false) {
  const tag = document.createElement("span");
  tag.className = hot ? "tag is-hot" : "tag";
  tag.textContent = text;
  return tag;
}

function roomLabel(roomId) {
  const room = ROOMS.find((item) => item.id === roomId);
  return room ? room.label : "シール";
}

function wireEvents() {
  els.mapScreen.addEventListener("click", (event) => {
    const button = event.target.closest("[data-room-id]");
    if (button) {
      showRoom(button.dataset.roomId);
      return;
    }
    const floorButton = event.target.closest("[data-floor-id]");
    if (!floorButton) return;
    const exit = FLOOR_EXITS.find((item) => item.id === floorButton.dataset.floorId);
    showMapNotice(exit ? `${exit.label}は ${exit.status}` : "じゅんびちゅう");
  });

  els.backToMap.addEventListener("click", () => {
    showMap();
  });

  els.homeButton.addEventListener("click", () => {
    window.location.assign(new URL("../../play.html", BASE_URL).href);
  });

  if (els.roomTabs) {
    els.roomTabs.addEventListener("click", (event) => {
      const button = event.target.closest("[data-room-id]");
      if (!button) return;
      showRoom(button.dataset.roomId);
    });
  }

  els.carouselLayer.addEventListener("click", (event) => {
    if (performance.now() < state.suppressClickUntil) {
      event.preventDefault();
      return;
    }
    const button = event.target.closest(".carousel-item");
    if (!button) return;
    const index = Number(button.dataset.index || 0);
    if (index !== state.index) {
      goTo(index);
      return;
    }
    const sticker = state.filtered[state.index];
    if (sticker) openDetail(sticker);
  });

  els.prevButton.addEventListener("click", prev);
  els.nextButton.addEventListener("click", next);
  els.randomButton.addEventListener("click", () => {
    const total = state.filtered.length;
    if (!total) return;
    const nextIndex = Math.floor(Math.random() * total);
    goTo(nextIndex === state.index ? nextIndex + 1 : nextIndex);
  });

  els.carouselViewport.addEventListener("keydown", (event) => {
    if (event.key === "ArrowRight") {
      event.preventDefault();
      next();
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      prev();
    } else if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      const sticker = state.filtered[state.index];
      if (sticker) openDetail(sticker);
    }
  });

  els.carouselViewport.addEventListener("pointerdown", (event) => {
    cancelGlide();
    state.touchStartX = event.clientX;
    state.touchStartY = event.clientY;
    state.touchStartTime = performance.now();
    state.touchActive = true;
    state.touchPointerId = event.pointerId;
    els.app.classList.add("is-dragging");
    setDragOffset(0);
    if (typeof els.carouselViewport.setPointerCapture === "function") {
      els.carouselViewport.setPointerCapture(event.pointerId);
    }
  });

  els.carouselViewport.addEventListener("pointermove", (event) => {
    if (!state.touchActive || event.pointerId !== state.touchPointerId) return;
    const dx = event.clientX - state.touchStartX;
    const dy = event.clientY - state.touchStartY;
    if (Math.abs(dx) < 3 || Math.abs(dx) < Math.abs(dy) * 0.8) return;
    const dragLimit = carouselStep() * 0.86;
    setDragOffset(clamp(dx, -dragLimit, dragLimit));
  });

  els.carouselViewport.addEventListener("pointerup", (event) => {
    if (!state.touchActive) return;
    state.touchActive = false;
    state.touchPointerId = 0;
    const dx = event.clientX - state.touchStartX;
    const dy = event.clientY - state.touchStartY;
    resetDragOffset();
    if (Math.abs(dx) < 36 || Math.abs(dx) < Math.abs(dy) * 1.2) return;
    const elapsed = Math.max(performance.now() - state.touchStartTime, 16);
    const velocity = Math.abs(dx) / elapsed;
    const projectedDistance = Math.abs(dx) + velocity * 170;
    const maxJump = Math.max(1, Math.min(6, state.filtered.length - 1));
    const jump = clamp(Math.round(projectedDistance / carouselStep()), 1, maxJump);
    glideBy(dx < 0 ? jump : -jump);
  });

  els.carouselViewport.addEventListener("pointercancel", () => {
    state.touchActive = false;
    state.touchPointerId = 0;
    resetDragOffset();
  });

  els.closeDetail.addEventListener("click", closeDetail);
  els.detailOverlay.addEventListener("click", (event) => {
    if (event.target === els.detailOverlay) closeDetail();
  });

  window.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && !els.detailOverlay.hidden) closeDetail();
  });

  window.addEventListener("popstate", () => {
    const roomId = readInitialRoomId();
    if (roomId) showRoom(roomId, { updateUrl: false });
    else showMap({ updateUrl: false });
  });

  window.addEventListener("resize", updateCarouselLayout);
}

function showMapNotice(message) {
  if (!els.mapNotice) return;
  window.clearTimeout(state.mapNoticeTimer);
  els.mapNotice.textContent = message;
  els.mapNotice.classList.add("is-visible");
  state.mapNoticeTimer = window.setTimeout(hideMapNotice, 1800);
}

function hideMapNotice() {
  if (!els.mapNotice) return;
  window.clearTimeout(state.mapNoticeTimer);
  state.mapNoticeTimer = 0;
  els.mapNotice.classList.remove("is-visible");
}

function assignRoom(sticker) {
  const text = `${sticker.id} ${sticker.name || ""} ${sticker.pageId}`.toLowerCase();

  if (sticker.pageId === "book-bonus") return "special";
  if (sticker.pageId === "starparodier" || hasAny(text, ["rocket", "ロケット", "うちゅう", "わくせい", "スター", "star", "planet", "space", "drone"])) return "space";
  if (sticker.pageId === "oto" || sticker.pageId === "quiz-sound" || hasAny(text, ["おんぷ", "ベル", "たいこ", "ボタン", "おみみ", "うたう", "メガホン", "voice", "ear", "bell", "taiko"])) return "sounds";
  if (hasAny(text, ["ごはん", "たまご", "からあげ", "ブロッコリー", "ウインナー", "いちご", "ランチ", "べんとう", "おかし", "キノコ", "food", "rice", "tamago", "karaage", "broccoli", "wiener", "strawberry", "lunch", "cookie", "mushroom"])) return "food";
  if (hasAny(text, ["スタンプ", "メダル", "バッジ", "はなまる", "badge", "medal", "stamp"])) return "special";
  if (hasAny(text, ["かぎ", "カギ", "はしご", "ランタン", "どんぐりぶくろ", "グローブ", "ピック", "カップ", "メモ", "たて", "しんじゅ", "かい", "すなだま", "あわ", "ふたば", "あのもじ", "key", "ladder", "lantern", "glove", "pick", "cup", "memo", "shield", "pearl", "shell", "sandball", "bubble", "sprout"])) return "tools";
  if (hasAny(text, ["ポノ", "ぽの", "はかせ", "スタッフ", "ミルマル", "ネジ", "ケロッチ", "ガオーン", "ブレイン", "メカ", "ドローン", "おんなのこ", "おとこのこ", "pono", "hakase", "staff", "milmaru", "robot", "gaohn", "brain", "mecha"])) return "characters";
  if (hasAny(text, ["ムシ", "むし", "バッタ", "ちょうちょ", "カニ", "うさぎ", "くじら", "アメンボ", "カブト", "ハチ", "しか", "アライグマ", "わん", "ねこ", "りす", "あひる", "ことり", "カエル", "ヤドカリ", "イソギンチャク", "エビ", "ヒトデ", "マンタ", "ウミガメ", "カブトガニ", "クマノミ", "イカ", "ジンベエ", "タコ", "いぬ", "キリン", "ライオン", "ペンギン", "キツネ", "リス", "こじか", "アヒル", "ハリネズミ", "batta", "chocho", "kani", "rabbit", "kujira", "amenbo", "kabuto", "hachi", "shika", "raccoon", "dog", "cat", "squirrel", "duck", "bird", "frog", "crab", "anemone", "shrimp", "starfish", "manta", "turtle", "fish", "squid", "whale", "octopus", "giraffe", "lion", "penguin", "fox", "hedgehog"])) return "creatures";
  if (sticker.pageId === "puzzle" || sticker.pageId === "writing-mori") return "characters";
  return "tools";
}

function readInitialRoomId() {
  const params = new URLSearchParams(window.location.search);
  const requested = params.get("room") || params.get("category") || window.location.hash.replace("#", "");
  if (ROOMS.some((room) => room.id === requested)) return requested;
  return "";
}

function hasAny(text, needles) {
  return needles.some((needle) => text.includes(String(needle).toLowerCase()));
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}
