#!/usr/bin/env python3
"""
Regenerate Prototypes/StickerExhibitionCarousel/sticker-metrics.js from the
current assets/data/game-stickers.json + the actual sticker PNGs.

Measures, per sticker PNG, the "opaque pixel" footprint (alpha >= threshold):
  - natural canvas width/height
  - opaque bounding box (x, y, w, h)
  - opaque pixel count (area)

These feed the sticker-size normalization formula in main.js
(stickerDisplayMetrics), which sizes each sticker's carousel/detail frame by
actual opaque-pixel footprint instead of raw canvas aspect ratio, so sparsely
padded PNGs no longer render abnormally large/small relative to tightly
cropped ones.

Output format (compact, no whitespace beyond what's needed):
  window.STICKER_METRICS = {
    "<sticker_id>": [width, height, bboxX, bboxY, bboxW, bboxH, area],
    ...
  };

Re-run this script whenever sticker PNGs are added/replaced:
  python scripts/generate_sticker_metrics.py

This script only READS the PNGs; it never modifies them.
"""
import json
import os
import sys

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow is required (pip install Pillow)", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STICKERS_JSON = os.path.join(REPO_ROOT, "assets", "data", "game-stickers.json")
OUT_JS = os.path.join(
    REPO_ROOT, "Prototypes", "StickerExhibitionCarousel", "sticker-metrics.js"
)

ALPHA_THRESHOLD = 10  # out of 255; matches the exploratory measurement pass


def extract_stickers():
    with open(STICKERS_JSON, encoding="utf-8") as f:
        data = json.load(f)
    entries = []
    for page_key, page in data.get("pages", {}).items():
        for s in page.get("stickers", []):
            entries.append({
                "page": page_key,
                "id": s.get("id"),
                "img": s.get("img"),
            })
    return entries


def measure_one(abs_path):
    """Returns (width, height, bboxX, bboxY, bboxW, bboxH, area) or None if
    the image is fully transparent (no sticker metrics emitted for it)."""
    with Image.open(abs_path) as im:
        im = im.convert("RGBA")
        w, h = im.size
        alpha = im.getchannel("A")
        mask = alpha.point(lambda a: 255 if a >= ALPHA_THRESHOLD else 0)
        bbox = mask.getbbox()
        if bbox is None:
            return None

        hist = mask.histogram()
        opaque_count = hist[255] if len(hist) > 255 else 0

        left, top, right, bottom = bbox
        bbox_w = right - left
        bbox_h = bottom - top

        return (w, h, left, top, bbox_w, bbox_h, opaque_count)


def main():
    entries = extract_stickers()
    metrics = {}
    errors = []

    for e in entries:
        sid = e["id"]
        rel_path = e["img"]
        if not sid or not rel_path:
            continue
        abs_path = os.path.join(REPO_ROOT, rel_path.replace("/", os.sep))
        if not os.path.isfile(abs_path):
            errors.append(f"{sid}: file not found ({rel_path})")
            continue
        try:
            measured = measure_one(abs_path)
        except Exception as ex:  # noqa: BLE001 - report and continue
            errors.append(f"{sid}: {ex}")
            continue
        if measured is None:
            errors.append(f"{sid}: fully transparent, skipped")
            continue
        metrics[sid] = list(measured)

    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_sticker_metrics.py — do not edit by hand.")
    lines.append("// Regenerate with: python scripts/generate_sticker_metrics.py")
    lines.append(
        "// Format: id -> [naturalWidth, naturalHeight, bboxX, bboxY, bboxW, bboxH, opaqueArea]"
    )
    lines.append("window.STICKER_METRICS = {")
    for sid in sorted(metrics.keys()):
        w, h, bx, by, bw, bh, area = metrics[sid]
        lines.append(f'  "{sid}": [{w},{h},{bx},{by},{bw},{bh},{area}],')
    lines.append("};")
    lines.append("")

    with open(OUT_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"entries: {len(entries)}")
    print(f"measured: {len(metrics)}")
    print(f"errors: {len(errors)}")
    for err in errors:
        print(f"  ERROR: {err}")
    print(f"wrote: {OUT_JS}")


if __name__ == "__main__":
    main()
